### ISSUE TITLE
Funnel Nuevos Pedidos

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizePOSApp#1]
## Información rápida
- Funnel de `nuevos pedidos` eventos de tracking para analíticas

## ¿Qué cambia esto?
- [ ] [Botón de Historial](https://github.com/BizneMX/BizePOSApp/issues/2)
- [ ] [Botón de Nuevos Pedidos](https://github.com/BizneMX/BizePOSApp/issues/3)
- [ ] [Botón de Entregados](https://github.com/BizneMX/BizePOSApp/issues/4)

## ¿Por qué estás cambiando eso?
- Detectar interacción de las fondas/restaurantes con en la sección `Nuevos Pedidos`

## ¿Cómo se prueba?
- Una vez enviados los cambios en el código, podremos ver los eventos reflejados dentro de FireBase

## Capturas de pantalla (si corresponde)

![Screenshot 2024-09-26 at 11 23 48 p m  copy 2](https://github.com/user-attachments/assets/4bdfb71e-c716-4e7d-be07-6a1698ccea70)
