### ISSUE TITLE
Funnel Mi Perfil

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizePOSApp#12]
## Información rápida
- Funnel de `Mi Perfil` eventos de tracking para analíticas

## ¿Qué cambia esto?
- [ ] [Botón de Editar Perfil](https://github.com/BizneMX/BizePOSApp/issues/16)
- [ ] [Botón de Mi Horario](https://github.com/BizneMX/BizePOSApp/issues/17)
- [ ] [Botón de Mi Personal](https://github.com/BizneMX/BizePOSApp/issues/18)
- [ ] [Botón de Capacitación](https://github.com/BizneMX/BizePOSApp/issues/19)

## ¿Por qué estás cambiando eso?
- Detectar interacción de las fondas/restaurantes con en la sección `Mi Perfil`

## ¿Cómo se prueba?
- Una vez enviados los cambios en el código, podremos ver los eventos reflejados dentro de FireBase

## Capturas de pantalla (si corresponde)

![resumen copy 2](https://github.com/user-attachments/assets/36cfe1ad-c641-4322-abf6-9bcbf16c5ffa)
