### ISSUE TITLE
Funnel Menu del Día

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizePOSApp#7]
## Información rápida
- Funnel de `Menu del Día` eventos de tracking para analíticas

## ¿Qué cambia esto?
- [ ] [Botón de Comida del Dia](https://github.com/BizneMX/BizePOSApp/issues/8)
- [ ] [Botón de Alimentos y Bebidas](https://github.com/BizneMX/BizePOSApp/issues/9)
- [ ] [Botón de Especialidades y Promociones](https://github.com/BizneMX/BizePOSApp/issues/10)
- [ ] [Botón de Comida de Mañana](https://github.com/BizneMX/BizePOSApp/issues/11)

## ¿Por qué estás cambiando eso?
- Detectar interacción de las fondas/restaurantes con en la sección ` Menu del Día`

## ¿Cómo se prueba?
- Una vez enviados los cambios en el código, podremos ver los eventos reflejados dentro de FireBase

## Capturas de pantalla (si corresponde)

![resumen copy](https://github.com/user-attachments/assets/608571d4-6bac-4aec-a58b-2d4dce3e16cb)
